r"""Fix precursor charge issues based on verification CSV reports.

Run after ``verify_precursor_charges_and_acq_type.py`` so DIA files with
known charges and DDA rows with unknown charges can be removed.

PURPOSE:
========
This script reads the CSV reports generated by verify_precursor_charges_and_acq_type.py
and applies fixes:

- DIA files with non-zero precursor charges: Delete the entire file
- DDA files with zero precursor charges: Drop those rows, write back to same location
- If a DDA file becomes empty after filtering, delete it
- If a project folder becomes empty after deletions, remove the folder
- Null/unknown error types are not fatal; they are logged as warnings at the end

CLI::

    python scripts/verification/fix_precursor_charges_from_reports.py --help
    python scripts/verification/fix_precursor_charges_from_reports.py \
        --input-dir <data-root>/lcfm/ \
        --report-dir verify_precursor_charge_and_acq_type_lcfm
    python scripts/verification/fix_precursor_charges_from_reports.py \
        --input-dir <data-root>/lcfm/ \
        --report-dir verify_precursor_charge_and_acq_type_lcfm \
        --dry-run
"""

import os
import logging
import tempfile
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional, Set

import polars as pl
import typer

from scripts.verification.verify_precursor_charges_and_acq_type import (
    extract_file_name,
)

app = typer.Typer(
    help="Fix precursor charges from verification CSV reports",
    no_args_is_help=True,
    add_completion=False,
)

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

INPUT_DIR_OPTION = typer.Option(
    ...,
    "--input-dir",
    "-i",
    help="Input directory containing parquet/ipc files organised by project subfolders",
)
REPORT_DIR_OPTION = typer.Option(
    ...,
    "--report-dir",
    help="Directory containing incorrect_dia_files.csv and incorrect_dda_files.csv",
)
DRY_RUN_OPTION = typer.Option(
    False,
    "--dry-run",
    "-n",
    help="Log actions without making changes",
)


@dataclass
class CleanupStats:
    """Record deletions, rewrites, and leftover null/unknown warnings from a cleanup run."""

    dia_files_deleted: int = 0
    dda_files_rewritten: int = 0
    dda_files_deleted: int = 0
    dda_rows_dropped: int = 0
    project_folders_removed: int = 0
    deleted_files: Set[tuple] = field(default_factory=set)
    null_unknown_warnings: list = field(default_factory=list)


def load_csv_if_exists(path: Path) -> pl.DataFrame:
    """Tolerate a missing DIA or DDA report so cleanup can still run the other half.

    Args:
        path: Expected CSV path under the report directory.

    Returns:
        The loaded table, or an empty frame with the expected error schema.
    """
    if path.exists():
        return pl.read_csv(path)
    return pl.DataFrame(
        schema={
            "filename": pl.String,
            "project": pl.String,
            "error_type": pl.String,
            "num_error_rows": pl.Int64,
            "total_rows": pl.Int64,
        }
    )


def resolve_file_path(input_dir: Path, project: str, filename: str) -> Optional[Path]:
    """Map a report (project, filename) pair onto the parquet/IPC file on disk.

    Scans input_dir/project/ for .parquet or .ipc files where extract_file_name
    matches the given filename.

    Args:
        input_dir: Root with per-project data folders.
        project: Project folder name from the CSV.
        filename: Experiment stem from the CSV.

    Returns:
        The matching file path, or None if the project folder or file is gone.
    """
    project_dir = input_dir / project
    if not project_dir.is_dir():
        return None

    for file_path in project_dir.iterdir():
        if file_path.is_file() and (
            file_path.suffix == ".parquet" or file_path.suffix == ".ipc"
        ):
            if extract_file_name(str(file_path)) == filename:
                return file_path
    return None


def remove_empty_project_folder(
    input_dir: Path, project: str, dry_run: bool, stats: CleanupStats
) -> None:
    """Remove a project folder only after all of its data files have been deleted.

    Args:
        input_dir: Root containing project folders.
        project: Project folder that may now be empty.
        dry_run: Log the rmdir without performing it.
        stats: Cleanup counters updated when a folder would be or is removed.
    """
    project_dir = input_dir / project
    if not project_dir.exists():
        return

    if not any(project_dir.iterdir()):
        if dry_run:
            logger.info(f"[DRY-RUN] Would remove empty project folder: {project_dir}")
        else:
            project_dir.rmdir()
            logger.info(f"Removed empty project folder: {project_dir}")
        stats.project_folders_removed += 1


def delete_file(
    file_path: Path,
    project: str,
    filename: str,
    input_dir: Path,
    dry_run: bool,
    stats: CleanupStats,
    acquisition: str,
) -> None:
    """Delete a mislabelled DIA file (or emptied DDA file) and drop empty project folders.

    Args:
        file_path: Data file to unlink.
        project: Project folder used to prune empty directories.
        filename: Stem recorded so leftover warnings skip deleted files.
        input_dir: Root containing project folders.
        dry_run: Log the delete without unlinking.
        stats: Cleanup counters.
        acquisition: ``DIA`` or ``DDA`` for logging and counters.
    """
    if dry_run:
        logger.info(f"[DRY-RUN] Would delete {acquisition} file: {file_path}")
    else:
        file_path.unlink()
        logger.info(f"Deleted {acquisition} file: {file_path}")

    stats.deleted_files.add((project, filename))
    if acquisition == "DIA":
        stats.dia_files_deleted += 1
    else:
        stats.dda_files_deleted += 1

    remove_empty_project_folder(input_dir, project, dry_run, stats)


def _collect_null_unknown_warnings(
    error_types: set, project: str, filename: str, acquisition: str, stats: CleanupStats
) -> None:
    """Keep null/unknown charge issues as warnings rather than treating them as fatal."""
    for et in error_types:
        if et in ("null_precursor_charge", "unknown_precursor_charge"):
            stats.null_unknown_warnings.append(
                {
                    "project": project,
                    "filename": filename,
                    "acquisition": acquisition,
                    "error_type": et,
                }
            )


def _read_data_file(file_path: Path) -> pl.DataFrame:
    """Read parquet or IPC so DDA zero-charge filtering works for both formats."""
    if file_path.suffix == ".parquet":
        return pl.read_parquet(file_path)
    return pl.read_ipc(file_path)


def _filter_zero_charge_rows(df: pl.DataFrame, file_path: Path) -> pl.DataFrame:
    """Drop DDA rows whose precursor charge is 0 (unknown), matching the verification policy."""
    dtype = df["precursor_charge"].dtype
    if dtype == pl.Int64:
        return df.filter(pl.col("precursor_charge") != 0)
    if dtype == pl.String:
        return df.filter(pl.col("precursor_charge") != "0")
    raise ValueError(f"Unexpected precursor_charge dtype {dtype} in {file_path}")


def _atomic_write_file(df: pl.DataFrame, file_path: Path) -> None:
    """Replace parquet/IPC only after a full write so a crash cannot leave a truncated file."""
    temp_fd, temp_path_str = tempfile.mkstemp(
        suffix=file_path.suffix, dir=file_path.parent
    )
    os.close(temp_fd)
    temp_path = Path(temp_path_str)

    try:
        if file_path.suffix == ".parquet":
            df.write_parquet(temp_path)
        else:
            df.write_ipc(temp_path)
        os.replace(temp_path, file_path)
    except Exception:
        if temp_path.exists():
            temp_path.unlink()
        raise


def _resolve_file_or_raise(
    input_dir: Path, project: str, filename: str, acquisition: str
) -> Path:
    """Fail loudly when a report row cannot be matched, so stale CSVs are not silently skipped."""
    file_path = resolve_file_path(input_dir, project, filename)
    if file_path is None:
        raise FileNotFoundError(
            f"Cannot resolve {acquisition} file for project={project}, "
            f"filename={filename}. CSV may be stale or input-dir incorrect."
        )
    return file_path


def process_dia_files(
    dia_df: pl.DataFrame, input_dir: Path, dry_run: bool, stats: CleanupStats
) -> None:
    """Delete DIA files that have non-zero precursor charges (charge should be unknown).

    Args:
        dia_df: Rows from ``incorrect_dia_files.csv``.
        input_dir: Root with per-project data files.
        dry_run: Log deletes without unlinking.
        stats: Cleanup counters and leftover warnings.
    """
    if dia_df.is_empty():
        logger.info("No DIA errors to process")
        return

    grouped = dia_df.group_by(["project", "filename"]).agg(
        pl.col("error_type").alias("error_types")
    )

    for row in grouped.iter_rows(named=True):
        project = row["project"]
        filename = row["filename"]
        error_types = set(row["error_types"])

        if "non_zero_precursor_charge" in error_types:
            file_path = _resolve_file_or_raise(input_dir, project, filename, "DIA")
            delete_file(file_path, project, filename, input_dir, dry_run, stats, "DIA")
        else:
            _collect_null_unknown_warnings(error_types, project, filename, "DIA", stats)


def _rewrite_dda_file(
    file_path: Path,
    project: str,
    filename: str,
    dry_run: bool,
    stats: CleanupStats,
    input_dir: Path,
) -> bool:
    """Drop zero-charge DDA rows and delete the file if nothing labelled remains."""
    df = _read_data_file(file_path)
    original_rows = len(df)

    df_filtered = _filter_zero_charge_rows(df, file_path)
    rows_dropped = original_rows - len(df_filtered)
    stats.dda_rows_dropped += rows_dropped

    if len(df_filtered) == 0:
        delete_file(file_path, project, filename, input_dir, dry_run, stats, "DDA")
        return True

    if dry_run:
        logger.info(
            f"[DRY-RUN] Would rewrite {file_path}, dropping {rows_dropped} rows"
        )
    else:
        _atomic_write_file(df_filtered, file_path)
        logger.info(
            f"Rewrote {file_path}, dropped {rows_dropped} rows "
            f"({len(df_filtered)} remaining)"
        )

    stats.dda_files_rewritten += 1
    return False


def process_dda_files(
    dda_df: pl.DataFrame, input_dir: Path, dry_run: bool, stats: CleanupStats
) -> None:
    """Drop DDA rows with zero precursor charge; delete the file if it becomes empty.

    Args:
        dda_df: Rows from ``incorrect_dda_files.csv``.
        input_dir: Root with per-project data files.
        dry_run: Log rewrites without writing.
        stats: Cleanup counters and leftover warnings.
    """
    if dda_df.is_empty():
        logger.info("No DDA errors to process")
        return

    grouped = dda_df.group_by(["project", "filename"]).agg(
        pl.col("error_type").alias("error_types")
    )

    for row in grouped.iter_rows(named=True):
        project = row["project"]
        filename = row["filename"]
        error_types = set(row["error_types"])

        if "zero_precursor_charge" not in error_types:
            _collect_null_unknown_warnings(error_types, project, filename, "DDA", stats)
            continue

        file_path = _resolve_file_or_raise(input_dir, project, filename, "DDA")
        deleted = _rewrite_dda_file(
            file_path, project, filename, dry_run, stats, input_dir
        )

        if not deleted:
            _collect_null_unknown_warnings(error_types, project, filename, "DDA", stats)


def log_warnings(stats: CleanupStats) -> None:
    """Surface null/unknown charges that cleanup did not fix (unless the file was deleted).

    Args:
        stats: Warning list and set of files already deleted.
    """
    warnings_to_log = [
        w
        for w in stats.null_unknown_warnings
        if (w["project"], w["filename"]) not in stats.deleted_files
    ]

    if warnings_to_log:
        logger.warning(
            f"The following {len(warnings_to_log)} file(s) have null or unknown "
            "precursor_charge values that were not addressed by this cleanup:"
        )
        for w in warnings_to_log:
            logger.warning(
                f"  - {w['acquisition']} file {w['project']}/{w['filename']}: {w['error_type']}"
            )


def run_cleanup(input_dir: str, report_dir: str, dry_run: bool) -> CleanupStats:
    """Apply DIA-delete / DDA-filter policy from the verification CSVs.

    Args:
        input_dir: Root containing parquet/IPC files by project.
        report_dir: Directory with ``incorrect_dia_files.csv`` and ``incorrect_dda_files.csv``.
        dry_run: Log actions without changing files.

    Returns:
        Counters for the cleanup summary.

    Raises:
        ValueError: When input_dir or report_dir does not exist.
    """
    input_path = Path(input_dir)
    report_path = Path(report_dir)

    if not input_path.is_dir():
        raise ValueError(f"Input directory does not exist: {input_path}")
    if not report_path.is_dir():
        raise ValueError(f"Report directory does not exist: {report_path}")

    dia_csv = report_path / "incorrect_dia_files.csv"
    dda_csv = report_path / "incorrect_dda_files.csv"

    dia_df = load_csv_if_exists(dia_csv)
    dda_df = load_csv_if_exists(dda_csv)

    logger.info(f"Loaded {len(dia_df)} DIA error rows, {len(dda_df)} DDA error rows")

    stats = CleanupStats()

    if dry_run:
        logger.info("DRY RUN MODE - no changes will be made")

    process_dia_files(dia_df, input_path, dry_run, stats)
    process_dda_files(dda_df, input_path, dry_run, stats)
    log_warnings(stats)

    logger.info("Cleanup summary:")
    logger.info(f"  DIA files deleted: {stats.dia_files_deleted}")
    logger.info(f"  DDA files rewritten: {stats.dda_files_rewritten}")
    logger.info(f"  DDA files deleted (empty after filter): {stats.dda_files_deleted}")
    logger.info(f"  DDA rows dropped total: {stats.dda_rows_dropped}")
    logger.info(f"  Project folders removed: {stats.project_folders_removed}")

    return stats


@app.command()
def main(
    input_dir: str = INPUT_DIR_OPTION,
    report_dir: str = REPORT_DIR_OPTION,
    dry_run: bool = DRY_RUN_OPTION,
) -> None:
    """Fix precursor charges from verification CSVs: delete bad DIA files, drop zero-charge DDA rows.

    Args:
        input_dir: Input directory containing parquet/ipc files organised by project subfolders.
        report_dir: Directory containing incorrect_dia_files.csv and incorrect_dda_files.csv.
        dry_run: Log actions without making changes.
    """
    run_cleanup(input_dir=input_dir, report_dir=report_dir, dry_run=dry_run)


if __name__ == "__main__":
    app()
